/*set global time_zone = '-3:00';*/

DROP DATABASE MDB_OWNER;

CREATE DATABASE MDB_OWNER 
/*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ 
/*!80016 DEFAULT ENCRYPTION='N' */;

USE MDB_OWNER;

CREATE TABLE USERS
(
  ID int NOT NULL AUTO_INCREMENT,
  NAME varchar(45) NOT NULL,
  EMAIL varchar(45) NOT NULL,
  PASSWORD varchar(45) NOT NULL,
  ROLE varchar(45),
  PRIMARY KEY (ID)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE COUNTRY 
(
  ID int NOT NULL AUTO_INCREMENT,
  NAME varchar(45) NOT NULL,
  PRIMARY KEY (ID)
) 
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE GENRE
(
  ID int NOT NULL AUTO_INCREMENT,
  NAME varchar(45) NOT NULL,
  PRIMARY KEY (ID)
)
 ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
 
CREATE TABLE MOVIE 
(
  ID int NOT NULL AUTO_INCREMENT,
  NAME varchar(45) NOT NULL,
  NAME_NATIVE varchar(45) NOT NULL,
  RELEASE_YEAR int NOT NULL,
  RATING int NOT NULL,
  PRICE int NOT NULL,
  DESCRIPTION varchar(45) NOT NULL,
  PICTURE_PATH varchar(45) NOT NULL,
  PRIMARY KEY (ID)
) 
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE REVIEW
(
  ID int NOT NULL AUTO_INCREMENT,
  MOVIE_ID int,
  REVIEW_TEXT varchar(45) NOT NULL,
  USER_ID int,
  PRIMARY KEY (ID),  
  CONSTRAINT MOVIE_ID FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE ON UPDATE CASCADE
) 
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE MOVIE_COUNTRY
 (
  ID int NOT NULL AUTO_INCREMENT,
  MOVIE_ID int,
  COUNTRY_ID int,
  PRIMARY KEY (ID),
  CONSTRAINT COUNTRY_MK_ID FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT MOVIE_MK_ID FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE (ID) ON DELETE CASCADE ON UPDATE CASCADE
) 
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE MOVIE_GENRE
(
  ID int NOT NULL AUTO_INCREMENT,
  MOVIE_ID int,
  GENRE_ID int,
  PRIMARY KEY (ID),
  CONSTRAINT GENRE_MG_ID FOREIGN KEY (GENRE_ID) REFERENCES GENRE (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT MOVIE_MG_ID FOREIGN KEY (MOVIE_ID) REFERENCES movie (ID) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;








